# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536b5ba857e0ba93e5e74c6a1af91d49260d65c5ac26ab9966c42cfb3c17e4e3606a7d0cde3ada0137dde72dc3f124b28dbc3cecbbc65351c5e2ec7becdc931d

test:
  secret_key_base: 336562e40a111deff494ee2d3253482fe1f5910d1a7c11a0c010155af4c50fb7b4665e930a42d4faf2cae41f08466d0f7fdb9fa1039d334a09ab563ac54e63f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
